// Code generated by protoc-gen-go. DO NOT EDIT.
// source: batch_job.proto

package pb

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 任务状态
type JobStatus int32

const (
	JobStatus_Created    JobStatus = 0
	JobStatus_WaitBizRun JobStatus = 1
	JobStatus_Running    JobStatus = 2
	JobStatus_Finished   JobStatus = 3
	JobStatus_Stopping   JobStatus = 4
	JobStatus_Stopped    JobStatus = 5
)

var JobStatus_name = map[int32]string{
	0: "Created",
	1: "WaitBizRun",
	2: "Running",
	3: "Finished",
	4: "Stopping",
	5: "Stopped",
}

var JobStatus_value = map[string]int32{
	"Created":    0,
	"WaitBizRun": 1,
	"Running":    2,
	"Finished":   3,
	"Stopping":   4,
	"Stopped":    5,
}

func (x JobStatus) String() string {
	return proto.EnumName(JobStatus_name, int32(x))
}

func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{0}
}

// 数据的日志类型
type DataLogType int32

const (
	DataLogType_Debug DataLogType = 0
	DataLogType_Info  DataLogType = 1
	DataLogType_Warn  DataLogType = 2
	DataLogType_Err   DataLogType = 3
)

var DataLogType_name = map[int32]string{
	0: "Debug",
	1: "Info",
	2: "Warn",
	3: "Err",
}

var DataLogType_value = map[string]int32{
	"Debug": 0,
	"Info":  1,
	"Warn":  2,
	"Err":   3,
}

func (x DataLogType) String() string {
	return proto.EnumName(DataLogType_name, int32(x))
}

func (DataLogType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{1}
}

type AdminRegistryBizReq struct {
	BizType              int32    `protobuf:"varint,1,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
	BizName              string   `protobuf:"bytes,2,opt,name=biz_name,json=bizName,proto3" json:"biz_name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	RateSec              int32    `protobuf:"varint,4,opt,name=rate_sec,json=rateSec,proto3" json:"rate_sec,omitempty"`
	CbBeforeCreate       string   `protobuf:"bytes,5,opt,name=cb_before_create,json=cbBeforeCreate,proto3" json:"cb_before_create,omitempty"`
	CbBeforeRun          string   `protobuf:"bytes,6,opt,name=cb_before_run,json=cbBeforeRun,proto3" json:"cb_before_run,omitempty"`
	CbProcess            string   `protobuf:"bytes,7,opt,name=cb_process,json=cbProcess,proto3" json:"cb_process,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminRegistryBizReq) Reset()         { *m = AdminRegistryBizReq{} }
func (m *AdminRegistryBizReq) String() string { return proto.CompactTextString(m) }
func (*AdminRegistryBizReq) ProtoMessage()    {}
func (*AdminRegistryBizReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{0}
}

func (m *AdminRegistryBizReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminRegistryBizReq.Unmarshal(m, b)
}
func (m *AdminRegistryBizReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminRegistryBizReq.Marshal(b, m, deterministic)
}
func (m *AdminRegistryBizReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminRegistryBizReq.Merge(m, src)
}
func (m *AdminRegistryBizReq) XXX_Size() int {
	return xxx_messageInfo_AdminRegistryBizReq.Size(m)
}
func (m *AdminRegistryBizReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminRegistryBizReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminRegistryBizReq proto.InternalMessageInfo

func (m *AdminRegistryBizReq) GetBizType() int32 {
	if m != nil {
		return m.BizType
	}
	return 0
}

func (m *AdminRegistryBizReq) GetBizName() string {
	if m != nil {
		return m.BizName
	}
	return ""
}

func (m *AdminRegistryBizReq) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AdminRegistryBizReq) GetRateSec() int32 {
	if m != nil {
		return m.RateSec
	}
	return 0
}

func (m *AdminRegistryBizReq) GetCbBeforeCreate() string {
	if m != nil {
		return m.CbBeforeCreate
	}
	return ""
}

func (m *AdminRegistryBizReq) GetCbBeforeRun() string {
	if m != nil {
		return m.CbBeforeRun
	}
	return ""
}

func (m *AdminRegistryBizReq) GetCbProcess() string {
	if m != nil {
		return m.CbProcess
	}
	return ""
}

type AdminRegistryBizRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminRegistryBizRsp) Reset()         { *m = AdminRegistryBizRsp{} }
func (m *AdminRegistryBizRsp) String() string { return proto.CompactTextString(m) }
func (*AdminRegistryBizRsp) ProtoMessage()    {}
func (*AdminRegistryBizRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{1}
}

func (m *AdminRegistryBizRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminRegistryBizRsp.Unmarshal(m, b)
}
func (m *AdminRegistryBizRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminRegistryBizRsp.Marshal(b, m, deterministic)
}
func (m *AdminRegistryBizRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminRegistryBizRsp.Merge(m, src)
}
func (m *AdminRegistryBizRsp) XXX_Size() int {
	return xxx_messageInfo_AdminRegistryBizRsp.Size(m)
}
func (m *AdminRegistryBizRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminRegistryBizRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AdminRegistryBizRsp proto.InternalMessageInfo

// 操作信息-请求
type OpInfoQ struct {
	OpSource             string   `protobuf:"bytes,1,opt,name=op_source,json=opSource,proto3" json:"op_source,omitempty"`
	OpUserid             string   `protobuf:"bytes,2,opt,name=op_userid,json=opUserid,proto3" json:"op_userid,omitempty"`
	OpUserName           string   `protobuf:"bytes,3,opt,name=op_user_name,json=opUserName,proto3" json:"op_user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpInfoQ) Reset()         { *m = OpInfoQ{} }
func (m *OpInfoQ) String() string { return proto.CompactTextString(m) }
func (*OpInfoQ) ProtoMessage()    {}
func (*OpInfoQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{2}
}

func (m *OpInfoQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpInfoQ.Unmarshal(m, b)
}
func (m *OpInfoQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpInfoQ.Marshal(b, m, deterministic)
}
func (m *OpInfoQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpInfoQ.Merge(m, src)
}
func (m *OpInfoQ) XXX_Size() int {
	return xxx_messageInfo_OpInfoQ.Size(m)
}
func (m *OpInfoQ) XXX_DiscardUnknown() {
	xxx_messageInfo_OpInfoQ.DiscardUnknown(m)
}

var xxx_messageInfo_OpInfoQ proto.InternalMessageInfo

func (m *OpInfoQ) GetOpSource() string {
	if m != nil {
		return m.OpSource
	}
	return ""
}

func (m *OpInfoQ) GetOpUserid() string {
	if m != nil {
		return m.OpUserid
	}
	return ""
}

func (m *OpInfoQ) GetOpUserName() string {
	if m != nil {
		return m.OpUserName
	}
	return ""
}

// 操作信息-响应
type OpInfoA struct {
	OpSource             string   `protobuf:"bytes,1,opt,name=op_source,json=opSource,proto3" json:"op_source,omitempty"`
	OpUserid             string   `protobuf:"bytes,2,opt,name=op_userid,json=opUserid,proto3" json:"op_userid,omitempty"`
	OpUserName           string   `protobuf:"bytes,3,opt,name=op_user_name,json=opUserName,proto3" json:"op_user_name,omitempty"`
	OpTime               int64    `protobuf:"varint,4,opt,name=op_time,json=opTime,proto3" json:"op_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpInfoA) Reset()         { *m = OpInfoA{} }
func (m *OpInfoA) String() string { return proto.CompactTextString(m) }
func (*OpInfoA) ProtoMessage()    {}
func (*OpInfoA) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{3}
}

func (m *OpInfoA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpInfoA.Unmarshal(m, b)
}
func (m *OpInfoA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpInfoA.Marshal(b, m, deterministic)
}
func (m *OpInfoA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpInfoA.Merge(m, src)
}
func (m *OpInfoA) XXX_Size() int {
	return xxx_messageInfo_OpInfoA.Size(m)
}
func (m *OpInfoA) XXX_DiscardUnknown() {
	xxx_messageInfo_OpInfoA.DiscardUnknown(m)
}

var xxx_messageInfo_OpInfoA proto.InternalMessageInfo

func (m *OpInfoA) GetOpSource() string {
	if m != nil {
		return m.OpSource
	}
	return ""
}

func (m *OpInfoA) GetOpUserid() string {
	if m != nil {
		return m.OpUserid
	}
	return ""
}

func (m *OpInfoA) GetOpUserName() string {
	if m != nil {
		return m.OpUserName
	}
	return ""
}

func (m *OpInfoA) GetOpTime() int64 {
	if m != nil {
		return m.OpTime
	}
	return 0
}

// 任务基础信息-响应
type BaseInfoA struct {
	JobId                int32    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	BizType              int32    `protobuf:"varint,2,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
	BizData              string   `protobuf:"bytes,3,opt,name=biz_data,json=bizData,proto3" json:"biz_data,omitempty"`
	ProcessDataTotal     int64    `protobuf:"varint,4,opt,name=process_data_total,json=processDataTotal,proto3" json:"process_data_total,omitempty"`
	ProcessedCount       int64    `protobuf:"varint,5,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	ErrLogCount          int64    `protobuf:"varint,6,opt,name=err_log_count,json=errLogCount,proto3" json:"err_log_count,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime           int64    `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Op                   *OpInfoA `protobuf:"bytes,9,opt,name=op,proto3" json:"op,omitempty"`
	StatusInfo           string   `protobuf:"bytes,10,opt,name=status_info,json=statusInfo,proto3" json:"status_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfoA) Reset()         { *m = BaseInfoA{} }
func (m *BaseInfoA) String() string { return proto.CompactTextString(m) }
func (*BaseInfoA) ProtoMessage()    {}
func (*BaseInfoA) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{4}
}

func (m *BaseInfoA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfoA.Unmarshal(m, b)
}
func (m *BaseInfoA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfoA.Marshal(b, m, deterministic)
}
func (m *BaseInfoA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfoA.Merge(m, src)
}
func (m *BaseInfoA) XXX_Size() int {
	return xxx_messageInfo_BaseInfoA.Size(m)
}
func (m *BaseInfoA) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfoA.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfoA proto.InternalMessageInfo

func (m *BaseInfoA) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *BaseInfoA) GetBizType() int32 {
	if m != nil {
		return m.BizType
	}
	return 0
}

func (m *BaseInfoA) GetBizData() string {
	if m != nil {
		return m.BizData
	}
	return ""
}

func (m *BaseInfoA) GetProcessDataTotal() int64 {
	if m != nil {
		return m.ProcessDataTotal
	}
	return 0
}

func (m *BaseInfoA) GetProcessedCount() int64 {
	if m != nil {
		return m.ProcessedCount
	}
	return 0
}

func (m *BaseInfoA) GetErrLogCount() int64 {
	if m != nil {
		return m.ErrLogCount
	}
	return 0
}

func (m *BaseInfoA) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BaseInfoA) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *BaseInfoA) GetOp() *OpInfoA {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *BaseInfoA) GetStatusInfo() string {
	if m != nil {
		return m.StatusInfo
	}
	return ""
}

// 日志-请求
type DataLogQ struct {
	DataId               string      `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Remark               string      `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Extend               string      `protobuf:"bytes,3,opt,name=extend,proto3" json:"extend,omitempty"`
	LogType              DataLogType `protobuf:"varint,4,opt,name=log_type,json=logType,proto3,enum=batch_job.DataLogType" json:"log_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DataLogQ) Reset()         { *m = DataLogQ{} }
func (m *DataLogQ) String() string { return proto.CompactTextString(m) }
func (*DataLogQ) ProtoMessage()    {}
func (*DataLogQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{5}
}

func (m *DataLogQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataLogQ.Unmarshal(m, b)
}
func (m *DataLogQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataLogQ.Marshal(b, m, deterministic)
}
func (m *DataLogQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataLogQ.Merge(m, src)
}
func (m *DataLogQ) XXX_Size() int {
	return xxx_messageInfo_DataLogQ.Size(m)
}
func (m *DataLogQ) XXX_DiscardUnknown() {
	xxx_messageInfo_DataLogQ.DiscardUnknown(m)
}

var xxx_messageInfo_DataLogQ proto.InternalMessageInfo

func (m *DataLogQ) GetDataId() string {
	if m != nil {
		return m.DataId
	}
	return ""
}

func (m *DataLogQ) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *DataLogQ) GetExtend() string {
	if m != nil {
		return m.Extend
	}
	return ""
}

func (m *DataLogQ) GetLogType() DataLogType {
	if m != nil {
		return m.LogType
	}
	return DataLogType_Debug
}

// 日志-响应
type DataLogA struct {
	DataId               string      `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Remark               string      `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Extend               string      `protobuf:"bytes,3,opt,name=extend,proto3" json:"extend,omitempty"`
	LogType              DataLogType `protobuf:"varint,4,opt,name=log_type,json=logType,proto3,enum=batch_job.DataLogType" json:"log_type,omitempty"`
	CreateTime           int64       `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DataLogA) Reset()         { *m = DataLogA{} }
func (m *DataLogA) String() string { return proto.CompactTextString(m) }
func (*DataLogA) ProtoMessage()    {}
func (*DataLogA) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{6}
}

func (m *DataLogA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataLogA.Unmarshal(m, b)
}
func (m *DataLogA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataLogA.Marshal(b, m, deterministic)
}
func (m *DataLogA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataLogA.Merge(m, src)
}
func (m *DataLogA) XXX_Size() int {
	return xxx_messageInfo_DataLogA.Size(m)
}
func (m *DataLogA) XXX_DiscardUnknown() {
	xxx_messageInfo_DataLogA.DiscardUnknown(m)
}

var xxx_messageInfo_DataLogA proto.InternalMessageInfo

func (m *DataLogA) GetDataId() string {
	if m != nil {
		return m.DataId
	}
	return ""
}

func (m *DataLogA) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *DataLogA) GetExtend() string {
	if m != nil {
		return m.Extend
	}
	return ""
}

func (m *DataLogA) GetLogType() DataLogType {
	if m != nil {
		return m.LogType
	}
	return DataLogType_Debug
}

func (m *DataLogA) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type AdminCreateJobReq struct {
	BizType              int32    `protobuf:"varint,1,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
	BizData              string   `protobuf:"bytes,2,opt,name=biz_data,json=bizData,proto3" json:"biz_data,omitempty"`
	BizProcessData       string   `protobuf:"bytes,3,opt,name=biz_process_data,json=bizProcessData,proto3" json:"biz_process_data,omitempty"`
	ProcessDataTotal     int64    `protobuf:"varint,4,opt,name=process_data_total,json=processDataTotal,proto3" json:"process_data_total,omitempty"`
	StartNow             bool     `protobuf:"varint,5,opt,name=start_now,json=startNow,proto3" json:"start_now,omitempty"`
	Op                   *OpInfoQ `protobuf:"bytes,6,opt,name=op,proto3" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminCreateJobReq) Reset()         { *m = AdminCreateJobReq{} }
func (m *AdminCreateJobReq) String() string { return proto.CompactTextString(m) }
func (*AdminCreateJobReq) ProtoMessage()    {}
func (*AdminCreateJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{7}
}

func (m *AdminCreateJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminCreateJobReq.Unmarshal(m, b)
}
func (m *AdminCreateJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminCreateJobReq.Marshal(b, m, deterministic)
}
func (m *AdminCreateJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminCreateJobReq.Merge(m, src)
}
func (m *AdminCreateJobReq) XXX_Size() int {
	return xxx_messageInfo_AdminCreateJobReq.Size(m)
}
func (m *AdminCreateJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminCreateJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminCreateJobReq proto.InternalMessageInfo

func (m *AdminCreateJobReq) GetBizType() int32 {
	if m != nil {
		return m.BizType
	}
	return 0
}

func (m *AdminCreateJobReq) GetBizData() string {
	if m != nil {
		return m.BizData
	}
	return ""
}

func (m *AdminCreateJobReq) GetBizProcessData() string {
	if m != nil {
		return m.BizProcessData
	}
	return ""
}

func (m *AdminCreateJobReq) GetProcessDataTotal() int64 {
	if m != nil {
		return m.ProcessDataTotal
	}
	return 0
}

func (m *AdminCreateJobReq) GetStartNow() bool {
	if m != nil {
		return m.StartNow
	}
	return false
}

func (m *AdminCreateJobReq) GetOp() *OpInfoQ {
	if m != nil {
		return m.Op
	}
	return nil
}

type AdminCreateJobRsp struct {
	JobId                int32    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminCreateJobRsp) Reset()         { *m = AdminCreateJobRsp{} }
func (m *AdminCreateJobRsp) String() string { return proto.CompactTextString(m) }
func (*AdminCreateJobRsp) ProtoMessage()    {}
func (*AdminCreateJobRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{8}
}

func (m *AdminCreateJobRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminCreateJobRsp.Unmarshal(m, b)
}
func (m *AdminCreateJobRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminCreateJobRsp.Marshal(b, m, deterministic)
}
func (m *AdminCreateJobRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminCreateJobRsp.Merge(m, src)
}
func (m *AdminCreateJobRsp) XXX_Size() int {
	return xxx_messageInfo_AdminCreateJobRsp.Size(m)
}
func (m *AdminCreateJobRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminCreateJobRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AdminCreateJobRsp proto.InternalMessageInfo

func (m *AdminCreateJobRsp) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type AdminStartJobReq struct {
	JobId                int32    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Op                   *OpInfoQ `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminStartJobReq) Reset()         { *m = AdminStartJobReq{} }
func (m *AdminStartJobReq) String() string { return proto.CompactTextString(m) }
func (*AdminStartJobReq) ProtoMessage()    {}
func (*AdminStartJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{9}
}

func (m *AdminStartJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminStartJobReq.Unmarshal(m, b)
}
func (m *AdminStartJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminStartJobReq.Marshal(b, m, deterministic)
}
func (m *AdminStartJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminStartJobReq.Merge(m, src)
}
func (m *AdminStartJobReq) XXX_Size() int {
	return xxx_messageInfo_AdminStartJobReq.Size(m)
}
func (m *AdminStartJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminStartJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminStartJobReq proto.InternalMessageInfo

func (m *AdminStartJobReq) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *AdminStartJobReq) GetOp() *OpInfoQ {
	if m != nil {
		return m.Op
	}
	return nil
}

type AdminStartJobRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminStartJobRsp) Reset()         { *m = AdminStartJobRsp{} }
func (m *AdminStartJobRsp) String() string { return proto.CompactTextString(m) }
func (*AdminStartJobRsp) ProtoMessage()    {}
func (*AdminStartJobRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{10}
}

func (m *AdminStartJobRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminStartJobRsp.Unmarshal(m, b)
}
func (m *AdminStartJobRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminStartJobRsp.Marshal(b, m, deterministic)
}
func (m *AdminStartJobRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminStartJobRsp.Merge(m, src)
}
func (m *AdminStartJobRsp) XXX_Size() int {
	return xxx_messageInfo_AdminStartJobRsp.Size(m)
}
func (m *AdminStartJobRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminStartJobRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AdminStartJobRsp proto.InternalMessageInfo

type AdminStopJobReq struct {
	JobId                int32    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Op                   *OpInfoQ `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminStopJobReq) Reset()         { *m = AdminStopJobReq{} }
func (m *AdminStopJobReq) String() string { return proto.CompactTextString(m) }
func (*AdminStopJobReq) ProtoMessage()    {}
func (*AdminStopJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{11}
}

func (m *AdminStopJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminStopJobReq.Unmarshal(m, b)
}
func (m *AdminStopJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminStopJobReq.Marshal(b, m, deterministic)
}
func (m *AdminStopJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminStopJobReq.Merge(m, src)
}
func (m *AdminStopJobReq) XXX_Size() int {
	return xxx_messageInfo_AdminStopJobReq.Size(m)
}
func (m *AdminStopJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminStopJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminStopJobReq proto.InternalMessageInfo

func (m *AdminStopJobReq) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *AdminStopJobReq) GetOp() *OpInfoQ {
	if m != nil {
		return m.Op
	}
	return nil
}

type AdminStopJobRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminStopJobRsp) Reset()         { *m = AdminStopJobRsp{} }
func (m *AdminStopJobRsp) String() string { return proto.CompactTextString(m) }
func (*AdminStopJobRsp) ProtoMessage()    {}
func (*AdminStopJobRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{12}
}

func (m *AdminStopJobRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminStopJobRsp.Unmarshal(m, b)
}
func (m *AdminStopJobRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminStopJobRsp.Marshal(b, m, deterministic)
}
func (m *AdminStopJobRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminStopJobRsp.Merge(m, src)
}
func (m *AdminStopJobRsp) XXX_Size() int {
	return xxx_messageInfo_AdminStopJobRsp.Size(m)
}
func (m *AdminStopJobRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminStopJobRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AdminStopJobRsp proto.InternalMessageInfo

type QueryJobBaseInfoReq struct {
	JobId                int32    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryJobBaseInfoReq) Reset()         { *m = QueryJobBaseInfoReq{} }
func (m *QueryJobBaseInfoReq) String() string { return proto.CompactTextString(m) }
func (*QueryJobBaseInfoReq) ProtoMessage()    {}
func (*QueryJobBaseInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{13}
}

func (m *QueryJobBaseInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryJobBaseInfoReq.Unmarshal(m, b)
}
func (m *QueryJobBaseInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryJobBaseInfoReq.Marshal(b, m, deterministic)
}
func (m *QueryJobBaseInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryJobBaseInfoReq.Merge(m, src)
}
func (m *QueryJobBaseInfoReq) XXX_Size() int {
	return xxx_messageInfo_QueryJobBaseInfoReq.Size(m)
}
func (m *QueryJobBaseInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryJobBaseInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryJobBaseInfoReq proto.InternalMessageInfo

func (m *QueryJobBaseInfoReq) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type QueryJobBaseInfoRsp struct {
	BaseInfo             *BaseInfoA `protobuf:"bytes,1,opt,name=base_info,json=baseInfo,proto3" json:"base_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryJobBaseInfoRsp) Reset()         { *m = QueryJobBaseInfoRsp{} }
func (m *QueryJobBaseInfoRsp) String() string { return proto.CompactTextString(m) }
func (*QueryJobBaseInfoRsp) ProtoMessage()    {}
func (*QueryJobBaseInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{14}
}

func (m *QueryJobBaseInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryJobBaseInfoRsp.Unmarshal(m, b)
}
func (m *QueryJobBaseInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryJobBaseInfoRsp.Marshal(b, m, deterministic)
}
func (m *QueryJobBaseInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryJobBaseInfoRsp.Merge(m, src)
}
func (m *QueryJobBaseInfoRsp) XXX_Size() int {
	return xxx_messageInfo_QueryJobBaseInfoRsp.Size(m)
}
func (m *QueryJobBaseInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryJobBaseInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryJobBaseInfoRsp proto.InternalMessageInfo

func (m *QueryJobBaseInfoRsp) GetBaseInfo() *BaseInfoA {
	if m != nil {
		return m.BaseInfo
	}
	return nil
}

type QueryJobListReq struct {
	StartTime            int64    `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64    `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	OpUser               string   `protobuf:"bytes,3,opt,name=op_user,json=opUser,proto3" json:"op_user,omitempty"`
	BizType              []int32  `protobuf:"varint,4,rep,packed,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
	Page                 int32    `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryJobListReq) Reset()         { *m = QueryJobListReq{} }
func (m *QueryJobListReq) String() string { return proto.CompactTextString(m) }
func (*QueryJobListReq) ProtoMessage()    {}
func (*QueryJobListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{15}
}

func (m *QueryJobListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryJobListReq.Unmarshal(m, b)
}
func (m *QueryJobListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryJobListReq.Marshal(b, m, deterministic)
}
func (m *QueryJobListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryJobListReq.Merge(m, src)
}
func (m *QueryJobListReq) XXX_Size() int {
	return xxx_messageInfo_QueryJobListReq.Size(m)
}
func (m *QueryJobListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryJobListReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryJobListReq proto.InternalMessageInfo

func (m *QueryJobListReq) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *QueryJobListReq) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *QueryJobListReq) GetOpUser() string {
	if m != nil {
		return m.OpUser
	}
	return ""
}

func (m *QueryJobListReq) GetBizType() []int32 {
	if m != nil {
		return m.BizType
	}
	return nil
}

func (m *QueryJobListReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *QueryJobListReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type QueryJobListRsp struct {
	Total                int32        `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PageSize             int32        `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Line                 []*BaseInfoA `protobuf:"bytes,3,rep,name=line,proto3" json:"line,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueryJobListRsp) Reset()         { *m = QueryJobListRsp{} }
func (m *QueryJobListRsp) String() string { return proto.CompactTextString(m) }
func (*QueryJobListRsp) ProtoMessage()    {}
func (*QueryJobListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{16}
}

func (m *QueryJobListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryJobListRsp.Unmarshal(m, b)
}
func (m *QueryJobListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryJobListRsp.Marshal(b, m, deterministic)
}
func (m *QueryJobListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryJobListRsp.Merge(m, src)
}
func (m *QueryJobListRsp) XXX_Size() int {
	return xxx_messageInfo_QueryJobListRsp.Size(m)
}
func (m *QueryJobListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryJobListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryJobListRsp proto.InternalMessageInfo

func (m *QueryJobListRsp) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *QueryJobListRsp) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *QueryJobListRsp) GetLine() []*BaseInfoA {
	if m != nil {
		return m.Line
	}
	return nil
}

type QueryJobDataLogReq struct {
	JobId                int32       `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Page                 int32       `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32       `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	LogType              DataLogType `protobuf:"varint,4,opt,name=log_type,json=logType,proto3,enum=batch_job.DataLogType" json:"log_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QueryJobDataLogReq) Reset()         { *m = QueryJobDataLogReq{} }
func (m *QueryJobDataLogReq) String() string { return proto.CompactTextString(m) }
func (*QueryJobDataLogReq) ProtoMessage()    {}
func (*QueryJobDataLogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{17}
}

func (m *QueryJobDataLogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryJobDataLogReq.Unmarshal(m, b)
}
func (m *QueryJobDataLogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryJobDataLogReq.Marshal(b, m, deterministic)
}
func (m *QueryJobDataLogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryJobDataLogReq.Merge(m, src)
}
func (m *QueryJobDataLogReq) XXX_Size() int {
	return xxx_messageInfo_QueryJobDataLogReq.Size(m)
}
func (m *QueryJobDataLogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryJobDataLogReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryJobDataLogReq proto.InternalMessageInfo

func (m *QueryJobDataLogReq) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *QueryJobDataLogReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *QueryJobDataLogReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *QueryJobDataLogReq) GetLogType() DataLogType {
	if m != nil {
		return m.LogType
	}
	return DataLogType_Debug
}

type QueryJobDataLogRsp struct {
	Total                int32       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PageSize             int32       `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Log                  []*DataLogA `protobuf:"bytes,3,rep,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QueryJobDataLogRsp) Reset()         { *m = QueryJobDataLogRsp{} }
func (m *QueryJobDataLogRsp) String() string { return proto.CompactTextString(m) }
func (*QueryJobDataLogRsp) ProtoMessage()    {}
func (*QueryJobDataLogRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{18}
}

func (m *QueryJobDataLogRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryJobDataLogRsp.Unmarshal(m, b)
}
func (m *QueryJobDataLogRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryJobDataLogRsp.Marshal(b, m, deterministic)
}
func (m *QueryJobDataLogRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryJobDataLogRsp.Merge(m, src)
}
func (m *QueryJobDataLogRsp) XXX_Size() int {
	return xxx_messageInfo_QueryJobDataLogRsp.Size(m)
}
func (m *QueryJobDataLogRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryJobDataLogRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryJobDataLogRsp proto.InternalMessageInfo

func (m *QueryJobDataLogRsp) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *QueryJobDataLogRsp) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *QueryJobDataLogRsp) GetLog() []*DataLogA {
	if m != nil {
		return m.Log
	}
	return nil
}

type BizStartJobReq struct {
	JobId                int32    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BizStartJobReq) Reset()         { *m = BizStartJobReq{} }
func (m *BizStartJobReq) String() string { return proto.CompactTextString(m) }
func (*BizStartJobReq) ProtoMessage()    {}
func (*BizStartJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{19}
}

func (m *BizStartJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BizStartJobReq.Unmarshal(m, b)
}
func (m *BizStartJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BizStartJobReq.Marshal(b, m, deterministic)
}
func (m *BizStartJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BizStartJobReq.Merge(m, src)
}
func (m *BizStartJobReq) XXX_Size() int {
	return xxx_messageInfo_BizStartJobReq.Size(m)
}
func (m *BizStartJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BizStartJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_BizStartJobReq proto.InternalMessageInfo

func (m *BizStartJobReq) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type BizStartJobRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BizStartJobRsp) Reset()         { *m = BizStartJobRsp{} }
func (m *BizStartJobRsp) String() string { return proto.CompactTextString(m) }
func (*BizStartJobRsp) ProtoMessage()    {}
func (*BizStartJobRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{20}
}

func (m *BizStartJobRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BizStartJobRsp.Unmarshal(m, b)
}
func (m *BizStartJobRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BizStartJobRsp.Marshal(b, m, deterministic)
}
func (m *BizStartJobRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BizStartJobRsp.Merge(m, src)
}
func (m *BizStartJobRsp) XXX_Size() int {
	return xxx_messageInfo_BizStartJobRsp.Size(m)
}
func (m *BizStartJobRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BizStartJobRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BizStartJobRsp proto.InternalMessageInfo

type BizStopJobReq struct {
	JobId                int32    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BizStopJobReq) Reset()         { *m = BizStopJobReq{} }
func (m *BizStopJobReq) String() string { return proto.CompactTextString(m) }
func (*BizStopJobReq) ProtoMessage()    {}
func (*BizStopJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{21}
}

func (m *BizStopJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BizStopJobReq.Unmarshal(m, b)
}
func (m *BizStopJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BizStopJobReq.Marshal(b, m, deterministic)
}
func (m *BizStopJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BizStopJobReq.Merge(m, src)
}
func (m *BizStopJobReq) XXX_Size() int {
	return xxx_messageInfo_BizStopJobReq.Size(m)
}
func (m *BizStopJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BizStopJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_BizStopJobReq proto.InternalMessageInfo

func (m *BizStopJobReq) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type BizStopJobRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BizStopJobRsp) Reset()         { *m = BizStopJobRsp{} }
func (m *BizStopJobRsp) String() string { return proto.CompactTextString(m) }
func (*BizStopJobRsp) ProtoMessage()    {}
func (*BizStopJobRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{22}
}

func (m *BizStopJobRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BizStopJobRsp.Unmarshal(m, b)
}
func (m *BizStopJobRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BizStopJobRsp.Marshal(b, m, deterministic)
}
func (m *BizStopJobRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BizStopJobRsp.Merge(m, src)
}
func (m *BizStopJobRsp) XXX_Size() int {
	return xxx_messageInfo_BizStopJobRsp.Size(m)
}
func (m *BizStopJobRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BizStopJobRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BizStopJobRsp proto.InternalMessageInfo

type BizUpdateBizDataReq struct {
	JobId                int32    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	BizData              string   `protobuf:"bytes,2,opt,name=biz_data,json=bizData,proto3" json:"biz_data,omitempty"`
	BizProcessData       string   `protobuf:"bytes,3,opt,name=biz_process_data,json=bizProcessData,proto3" json:"biz_process_data,omitempty"`
	ProcessDataTotal     int64    `protobuf:"varint,4,opt,name=process_data_total,json=processDataTotal,proto3" json:"process_data_total,omitempty"`
	ProcessedCount       int64    `protobuf:"varint,5,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BizUpdateBizDataReq) Reset()         { *m = BizUpdateBizDataReq{} }
func (m *BizUpdateBizDataReq) String() string { return proto.CompactTextString(m) }
func (*BizUpdateBizDataReq) ProtoMessage()    {}
func (*BizUpdateBizDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{23}
}

func (m *BizUpdateBizDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BizUpdateBizDataReq.Unmarshal(m, b)
}
func (m *BizUpdateBizDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BizUpdateBizDataReq.Marshal(b, m, deterministic)
}
func (m *BizUpdateBizDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BizUpdateBizDataReq.Merge(m, src)
}
func (m *BizUpdateBizDataReq) XXX_Size() int {
	return xxx_messageInfo_BizUpdateBizDataReq.Size(m)
}
func (m *BizUpdateBizDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BizUpdateBizDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_BizUpdateBizDataReq proto.InternalMessageInfo

func (m *BizUpdateBizDataReq) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *BizUpdateBizDataReq) GetBizData() string {
	if m != nil {
		return m.BizData
	}
	return ""
}

func (m *BizUpdateBizDataReq) GetBizProcessData() string {
	if m != nil {
		return m.BizProcessData
	}
	return ""
}

func (m *BizUpdateBizDataReq) GetProcessDataTotal() int64 {
	if m != nil {
		return m.ProcessDataTotal
	}
	return 0
}

func (m *BizUpdateBizDataReq) GetProcessedCount() int64 {
	if m != nil {
		return m.ProcessedCount
	}
	return 0
}

type BizUpdateBizDataRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BizUpdateBizDataRsp) Reset()         { *m = BizUpdateBizDataRsp{} }
func (m *BizUpdateBizDataRsp) String() string { return proto.CompactTextString(m) }
func (*BizUpdateBizDataRsp) ProtoMessage()    {}
func (*BizUpdateBizDataRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{24}
}

func (m *BizUpdateBizDataRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BizUpdateBizDataRsp.Unmarshal(m, b)
}
func (m *BizUpdateBizDataRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BizUpdateBizDataRsp.Marshal(b, m, deterministic)
}
func (m *BizUpdateBizDataRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BizUpdateBizDataRsp.Merge(m, src)
}
func (m *BizUpdateBizDataRsp) XXX_Size() int {
	return xxx_messageInfo_BizUpdateBizDataRsp.Size(m)
}
func (m *BizUpdateBizDataRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BizUpdateBizDataRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BizUpdateBizDataRsp proto.InternalMessageInfo

type BizIncrProcessedNumReq struct {
	JobId                int32    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Num                  int64    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BizIncrProcessedNumReq) Reset()         { *m = BizIncrProcessedNumReq{} }
func (m *BizIncrProcessedNumReq) String() string { return proto.CompactTextString(m) }
func (*BizIncrProcessedNumReq) ProtoMessage()    {}
func (*BizIncrProcessedNumReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{25}
}

func (m *BizIncrProcessedNumReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BizIncrProcessedNumReq.Unmarshal(m, b)
}
func (m *BizIncrProcessedNumReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BizIncrProcessedNumReq.Marshal(b, m, deterministic)
}
func (m *BizIncrProcessedNumReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BizIncrProcessedNumReq.Merge(m, src)
}
func (m *BizIncrProcessedNumReq) XXX_Size() int {
	return xxx_messageInfo_BizIncrProcessedNumReq.Size(m)
}
func (m *BizIncrProcessedNumReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BizIncrProcessedNumReq.DiscardUnknown(m)
}

var xxx_messageInfo_BizIncrProcessedNumReq proto.InternalMessageInfo

func (m *BizIncrProcessedNumReq) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *BizIncrProcessedNumReq) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type BizIncrProcessedNumRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BizIncrProcessedNumRsp) Reset()         { *m = BizIncrProcessedNumRsp{} }
func (m *BizIncrProcessedNumRsp) String() string { return proto.CompactTextString(m) }
func (*BizIncrProcessedNumRsp) ProtoMessage()    {}
func (*BizIncrProcessedNumRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{26}
}

func (m *BizIncrProcessedNumRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BizIncrProcessedNumRsp.Unmarshal(m, b)
}
func (m *BizIncrProcessedNumRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BizIncrProcessedNumRsp.Marshal(b, m, deterministic)
}
func (m *BizIncrProcessedNumRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BizIncrProcessedNumRsp.Merge(m, src)
}
func (m *BizIncrProcessedNumRsp) XXX_Size() int {
	return xxx_messageInfo_BizIncrProcessedNumRsp.Size(m)
}
func (m *BizIncrProcessedNumRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BizIncrProcessedNumRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BizIncrProcessedNumRsp proto.InternalMessageInfo

type BizAddDataLogReq struct {
	JobId                int32       `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Log                  []*DataLogQ `protobuf:"bytes,2,rep,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BizAddDataLogReq) Reset()         { *m = BizAddDataLogReq{} }
func (m *BizAddDataLogReq) String() string { return proto.CompactTextString(m) }
func (*BizAddDataLogReq) ProtoMessage()    {}
func (*BizAddDataLogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{27}
}

func (m *BizAddDataLogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BizAddDataLogReq.Unmarshal(m, b)
}
func (m *BizAddDataLogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BizAddDataLogReq.Marshal(b, m, deterministic)
}
func (m *BizAddDataLogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BizAddDataLogReq.Merge(m, src)
}
func (m *BizAddDataLogReq) XXX_Size() int {
	return xxx_messageInfo_BizAddDataLogReq.Size(m)
}
func (m *BizAddDataLogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BizAddDataLogReq.DiscardUnknown(m)
}

var xxx_messageInfo_BizAddDataLogReq proto.InternalMessageInfo

func (m *BizAddDataLogReq) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *BizAddDataLogReq) GetLog() []*DataLogQ {
	if m != nil {
		return m.Log
	}
	return nil
}

type BizAddDataLogRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BizAddDataLogRsp) Reset()         { *m = BizAddDataLogRsp{} }
func (m *BizAddDataLogRsp) String() string { return proto.CompactTextString(m) }
func (*BizAddDataLogRsp) ProtoMessage()    {}
func (*BizAddDataLogRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c6eabe4c2b7788, []int{28}
}

func (m *BizAddDataLogRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BizAddDataLogRsp.Unmarshal(m, b)
}
func (m *BizAddDataLogRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BizAddDataLogRsp.Marshal(b, m, deterministic)
}
func (m *BizAddDataLogRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BizAddDataLogRsp.Merge(m, src)
}
func (m *BizAddDataLogRsp) XXX_Size() int {
	return xxx_messageInfo_BizAddDataLogRsp.Size(m)
}
func (m *BizAddDataLogRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BizAddDataLogRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BizAddDataLogRsp proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("batch_job.JobStatus", JobStatus_name, JobStatus_value)
	proto.RegisterEnum("batch_job.DataLogType", DataLogType_name, DataLogType_value)
	proto.RegisterType((*AdminRegistryBizReq)(nil), "batch_job.AdminRegistryBizReq")
	proto.RegisterType((*AdminRegistryBizRsp)(nil), "batch_job.AdminRegistryBizRsp")
	proto.RegisterType((*OpInfoQ)(nil), "batch_job.OpInfoQ")
	proto.RegisterType((*OpInfoA)(nil), "batch_job.OpInfoA")
	proto.RegisterType((*BaseInfoA)(nil), "batch_job.BaseInfoA")
	proto.RegisterType((*DataLogQ)(nil), "batch_job.DataLogQ")
	proto.RegisterType((*DataLogA)(nil), "batch_job.DataLogA")
	proto.RegisterType((*AdminCreateJobReq)(nil), "batch_job.AdminCreateJobReq")
	proto.RegisterType((*AdminCreateJobRsp)(nil), "batch_job.AdminCreateJobRsp")
	proto.RegisterType((*AdminStartJobReq)(nil), "batch_job.AdminStartJobReq")
	proto.RegisterType((*AdminStartJobRsp)(nil), "batch_job.AdminStartJobRsp")
	proto.RegisterType((*AdminStopJobReq)(nil), "batch_job.AdminStopJobReq")
	proto.RegisterType((*AdminStopJobRsp)(nil), "batch_job.AdminStopJobRsp")
	proto.RegisterType((*QueryJobBaseInfoReq)(nil), "batch_job.QueryJobBaseInfoReq")
	proto.RegisterType((*QueryJobBaseInfoRsp)(nil), "batch_job.QueryJobBaseInfoRsp")
	proto.RegisterType((*QueryJobListReq)(nil), "batch_job.QueryJobListReq")
	proto.RegisterType((*QueryJobListRsp)(nil), "batch_job.QueryJobListRsp")
	proto.RegisterType((*QueryJobDataLogReq)(nil), "batch_job.QueryJobDataLogReq")
	proto.RegisterType((*QueryJobDataLogRsp)(nil), "batch_job.QueryJobDataLogRsp")
	proto.RegisterType((*BizStartJobReq)(nil), "batch_job.BizStartJobReq")
	proto.RegisterType((*BizStartJobRsp)(nil), "batch_job.BizStartJobRsp")
	proto.RegisterType((*BizStopJobReq)(nil), "batch_job.BizStopJobReq")
	proto.RegisterType((*BizStopJobRsp)(nil), "batch_job.BizStopJobRsp")
	proto.RegisterType((*BizUpdateBizDataReq)(nil), "batch_job.BizUpdateBizDataReq")
	proto.RegisterType((*BizUpdateBizDataRsp)(nil), "batch_job.BizUpdateBizDataRsp")
	proto.RegisterType((*BizIncrProcessedNumReq)(nil), "batch_job.BizIncrProcessedNumReq")
	proto.RegisterType((*BizIncrProcessedNumRsp)(nil), "batch_job.BizIncrProcessedNumRsp")
	proto.RegisterType((*BizAddDataLogReq)(nil), "batch_job.BizAddDataLogReq")
	proto.RegisterType((*BizAddDataLogRsp)(nil), "batch_job.BizAddDataLogRsp")
}

func init() {
	proto.RegisterFile("batch_job.proto", fileDescriptor_12c6eabe4c2b7788)
}

var fileDescriptor_12c6eabe4c2b7788 = []byte{
	// 1538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xcf, 0x73, 0xd3, 0xc6,
	0x17, 0x47, 0x72, 0xfc, 0xeb, 0x99, 0x24, 0x62, 0x03, 0xc1, 0x51, 0x08, 0x98, 0xfd, 0xc2, 0xe0,
	0xc9, 0xb7, 0x83, 0x0b, 0x1d, 0x2e, 0xdc, 0x22, 0x68, 0xa7, 0xc9, 0x30, 0x94, 0x28, 0x50, 0xa6,
	0x3d, 0xd4, 0xa3, 0x1f, 0x8b, 0x11, 0xb5, 0xb5, 0x8b, 0x56, 0x82, 0xc6, 0x87, 0x1e, 0x3a, 0xd3,
	0x0e, 0xe7, 0xf6, 0x2f, 0xe8, 0xa9, 0x33, 0xfd, 0x6b, 0xca, 0xb4, 0x7f, 0x42, 0x6f, 0xbd, 0xf7,
	0x90, 0x53, 0x67, 0x77, 0x25, 0x5b, 0x92, 0xed, 0x10, 0x98, 0x76, 0x38, 0xe1, 0xdd, 0xcf, 0x47,
	0xef, 0xed, 0x7b, 0xfb, 0x79, 0xef, 0x2d, 0x81, 0x55, 0xd7, 0x89, 0xbd, 0xa7, 0xfd, 0x67, 0xd4,
	0xbd, 0xce, 0x22, 0x1a, 0x53, 0xd4, 0x9c, 0x6c, 0x98, 0x17, 0x06, 0x94, 0x0e, 0x86, 0xa4, 0xe7,
	0xb0, 0xa0, 0xe7, 0x84, 0x21, 0x8d, 0x9d, 0x38, 0xa0, 0x21, 0x57, 0x44, 0xf3, 0xfc, 0x0b, 0x67,
	0x18, 0xf8, 0x4e, 0x4c, 0x7a, 0xd9, 0x0f, 0x05, 0xe0, 0x9f, 0x75, 0x58, 0xdb, 0xf1, 0x47, 0x41,
	0x68, 0x93, 0x41, 0xc0, 0xe3, 0xe8, 0xd0, 0x0a, 0xc6, 0x36, 0x79, 0x8e, 0x30, 0x34, 0xdc, 0x60,
	0xdc, 0x8f, 0x0f, 0x19, 0x69, 0x6b, 0x1d, 0xad, 0x5b, 0xb5, 0xea, 0x47, 0xd6, 0x92, 0xa9, 0x77,
	0x4e, 0xd9, 0x75, 0x37, 0x18, 0x3f, 0x3c, 0x64, 0x24, 0xe3, 0x84, 0xce, 0x88, 0xb4, 0xf5, 0x8e,
	0xd6, 0x6d, 0x4a, 0x4e, 0xa4, 0x1b, 0x9a, 0xe4, 0xdc, 0x77, 0x46, 0x04, 0xad, 0x43, 0x2d, 0x22,
	0x23, 0x27, 0xfa, 0xba, 0x5d, 0x11, 0x0c, 0x3b, 0x5d, 0xa1, 0x0d, 0x68, 0x44, 0x4e, 0x4c, 0xfa,
	0x9c, 0x78, 0xed, 0x25, 0x61, 0xdf, 0xae, 0x8b, 0xf5, 0x01, 0xf1, 0xd0, 0x2d, 0x30, 0x3c, 0xb7,
	0xef, 0x92, 0x27, 0x34, 0x22, 0x7d, 0x2f, 0x22, 0x4e, 0x4c, 0xda, 0x55, 0x69, 0xbe, 0x75, 0x64,
	0x35, 0xa2, 0xda, 0x2b, 0x4d, 0xfb, 0x4d, 0xd3, 0xec, 0x15, 0xcf, 0xb5, 0x24, 0xe7, 0x8e, 0xa4,
	0xa0, 0x1e, 0x2c, 0x4f, 0x3f, 0x8b, 0x92, 0xb0, 0x5d, 0x9b, 0xfd, 0xa6, 0x95, 0x7d, 0x63, 0x27,
	0x21, 0xba, 0x06, 0xe0, 0xb9, 0x7d, 0x16, 0x51, 0x8f, 0x70, 0xde, 0xae, 0x4b, 0x76, 0xe3, 0xc8,
	0xaa, 0x46, 0x95, 0x57, 0x9a, 0x66, 0x37, 0x3d, 0xf7, 0x81, 0x82, 0xf0, 0xb9, 0x39, 0x29, 0xe2,
	0x0c, 0x13, 0xa8, 0x7f, 0xc6, 0x76, 0xc3, 0x27, 0x74, 0x1f, 0x6d, 0x42, 0x93, 0xb2, 0x3e, 0xa7,
	0x49, 0xe4, 0xa9, 0x74, 0x35, 0xed, 0x06, 0x65, 0x07, 0x72, 0x9d, 0x82, 0x09, 0x27, 0x51, 0xe0,
	0xab, 0x3c, 0x09, 0xf0, 0x91, 0x5c, 0xa3, 0x0e, 0x9c, 0x4e, 0x41, 0x95, 0x47, 0x95, 0x25, 0x50,
	0xb8, 0xc8, 0x20, 0xfe, 0x36, 0x73, 0xb3, 0xf3, 0x5f, 0xba, 0x41, 0xe7, 0xa1, 0x4e, 0x59, 0x3f,
	0x0e, 0x46, 0x44, 0xde, 0x47, 0xc5, 0xae, 0x51, 0xf6, 0x30, 0x18, 0x11, 0xfc, 0x5a, 0x87, 0xa6,
	0xe5, 0x70, 0xa2, 0x8e, 0x70, 0x0e, 0x6a, 0xcf, 0xa8, 0xdb, 0x0f, 0x7c, 0xa5, 0x0a, 0xbb, 0xfa,
	0x8c, 0xba, 0xbb, 0xbe, 0xb8, 0xce, 0x89, 0x5c, 0x74, 0x75, 0x9d, 0x99, 0x4a, 0x52, 0xc8, 0x77,
	0x62, 0x27, 0x75, 0x2b, 0xa0, 0xbb, 0x4e, 0xec, 0xa0, 0x0f, 0x00, 0xa5, 0xe9, 0x97, 0x70, 0x3f,
	0xa6, 0xb1, 0x33, 0x4c, 0xdd, 0x1b, 0x29, 0x22, 0x88, 0x0f, 0xc5, 0x3e, 0xba, 0x06, 0xab, 0xe9,
	0x1e, 0xf1, 0xfb, 0x1e, 0x4d, 0xc2, 0x58, 0xca, 0xa2, 0x62, 0xaf, 0x4c, 0xb6, 0xef, 0x88, 0x5d,
	0x84, 0x61, 0x99, 0x44, 0x51, 0x7f, 0x48, 0x07, 0x29, 0xad, 0x26, 0x69, 0x2d, 0x12, 0x45, 0xf7,
	0xe8, 0x40, 0x71, 0xd6, 0xa1, 0xc6, 0x63, 0x27, 0x4e, 0xd4, 0xc5, 0x57, 0xed, 0x74, 0x85, 0x2e,
	0x41, 0x4b, 0x49, 0x4e, 0xa5, 0xa2, 0x21, 0xbf, 0x04, 0xb5, 0x25, 0xd2, 0x81, 0x30, 0xe8, 0x94,
	0xb5, 0x9b, 0x1d, 0xad, 0xdb, 0xba, 0x89, 0xae, 0x4f, 0x0b, 0x32, 0xbd, 0x23, 0x5b, 0xa7, 0x4c,
	0x18, 0x51, 0xe6, 0xfa, 0x41, 0xf8, 0x84, 0xb6, 0x41, 0x25, 0x5b, 0x6d, 0x09, 0x16, 0xfe, 0x41,
	0x83, 0x86, 0x08, 0xec, 0x1e, 0x1d, 0xec, 0x8b, 0xcc, 0xcb, 0xe8, 0xd3, 0x9c, 0x36, 0xed, 0x9a,
	0x58, 0xee, 0xfa, 0xb9, 0xda, 0xd1, 0x0b, 0xb5, 0xb3, 0x0e, 0x35, 0xf2, 0x4d, 0x4c, 0x42, 0x3f,
	0xab, 0x29, 0xb5, 0x42, 0x37, 0xa0, 0x21, 0x62, 0x96, 0x97, 0x20, 0x92, 0xb8, 0x72, 0x73, 0x3d,
	0x77, 0xc0, 0xd4, 0x9f, 0xb8, 0x13, 0xbb, 0x3e, 0x54, 0x3f, 0xf0, 0x2f, 0xd3, 0x83, 0xec, 0xbc,
	0xcf, 0x83, 0x94, 0xf3, 0x5e, 0x2d, 0xe7, 0x1d, 0xff, 0xa5, 0xc1, 0x19, 0x59, 0x85, 0xaa, 0xdc,
	0xf7, 0xa8, 0x7b, 0xd2, 0x36, 0x95, 0x17, 0xa0, 0x5e, 0x14, 0x60, 0x17, 0x0c, 0x01, 0xe5, 0x45,
	0x98, 0x86, 0xb2, 0xe2, 0x06, 0xe3, 0x07, 0x53, 0x05, 0xbe, 0xa5, 0x54, 0x37, 0xa1, 0xc9, 0x63,
	0x27, 0x8a, 0xfb, 0x21, 0x7d, 0x29, 0x63, 0x69, 0xd8, 0x0d, 0xb9, 0x71, 0x9f, 0xbe, 0x4c, 0x15,
	0x54, 0x5b, 0xa0, 0xa0, 0x7d, 0xa1, 0x20, 0xbc, 0x3d, 0x13, 0x2c, 0x67, 0x0b, 0x6a, 0x0f, 0x7f,
	0x0e, 0x86, 0xe4, 0x1e, 0x08, 0x07, 0x69, 0x5e, 0x2e, 0x16, 0xa9, 0xd3, 0xac, 0xa4, 0xf5, 0xaa,
	0xce, 0xa0, 0x1f, 0x7b, 0x06, 0x54, 0xb6, 0xcb, 0x19, 0x7e, 0x04, 0xab, 0xe9, 0x1e, 0x65, 0xff,
	0xa2, 0xab, 0x33, 0x25, 0xb3, 0x9c, 0xe1, 0x5b, 0xb0, 0xb6, 0x9f, 0x90, 0xe8, 0x70, 0x8f, 0xba,
	0x59, 0xf7, 0x39, 0x81, 0x37, 0xfc, 0xe9, 0x9c, 0xcf, 0x38, 0x43, 0x37, 0xa0, 0xe9, 0x3a, 0x9c,
	0xa8, 0x7a, 0xd4, 0xe4, 0x59, 0xce, 0xe6, 0xce, 0x32, 0xe9, 0x6f, 0x76, 0xc3, 0x4d, 0x7f, 0xe2,
	0x3f, 0x34, 0x58, 0xcd, 0x4c, 0xdd, 0x0b, 0x78, 0x2c, 0xbc, 0x6f, 0x01, 0xa8, 0x7b, 0x95, 0x22,
	0xd5, 0xe4, 0xed, 0xab, 0x9b, 0x96, 0xbd, 0x61, 0x03, 0x1a, 0x24, 0xf4, 0x15, 0xa8, 0x4b, 0xb0,
	0x4e, 0x42, 0x5f, 0x42, 0xaa, 0xbd, 0x8a, 0x06, 0x9c, 0xd5, 0x8a, 0xea, 0xbd, 0xe8, 0xff, 0x39,
	0x05, 0x2f, 0x75, 0x2a, 0xdd, 0xaa, 0x65, 0x1c, 0x59, 0xcb, 0x3f, 0x6a, 0xd0, 0xd6, 0xb0, 0x8c,
	0xac, 0xab, 0x4d, 0xa5, 0xbc, 0x09, 0x4b, 0xcc, 0x19, 0xa8, 0xf2, 0xc8, 0xc5, 0x2e, 0x37, 0xd1,
	0x15, 0x68, 0x8a, 0x7f, 0xfb, 0x3c, 0x18, 0x13, 0x29, 0xaf, 0x8c, 0xd1, 0xad, 0xda, 0x0d, 0x81,
	0x1c, 0x04, 0x63, 0x82, 0xc3, 0x52, 0x54, 0x9c, 0xa1, 0xb3, 0x50, 0x55, 0x72, 0x4e, 0x65, 0x15,
	0x67, 0x1a, 0x9e, 0x9a, 0x53, 0x3d, 0x7d, 0x62, 0x05, 0x75, 0x61, 0x69, 0x18, 0x84, 0x62, 0x8e,
	0x54, 0x16, 0xa6, 0x52, 0x32, 0xf0, 0xaf, 0x1a, 0xa0, 0xcc, 0x61, 0x5a, 0xf9, 0x27, 0x51, 0x4d,
	0x16, 0xa9, 0xfe, 0xc6, 0x48, 0x2b, 0x0b, 0x22, 0x7d, 0x97, 0x76, 0x18, 0xce, 0x9e, 0xf5, 0xdd,
	0xf2, 0x73, 0x15, 0x2a, 0x43, 0x3a, 0x48, 0xd3, 0xb3, 0x36, 0xeb, 0x76, 0xc7, 0x16, 0x38, 0xfe,
	0x10, 0x56, 0xac, 0x60, 0xfc, 0x16, 0x85, 0x8b, 0x8d, 0xe2, 0x17, 0x9c, 0xe1, 0x1e, 0x2c, 0xcb,
	0x9d, 0x93, 0x16, 0x24, 0x5e, 0x2d, 0x7c, 0xc0, 0x19, 0x7e, 0xad, 0xc1, 0x9a, 0x15, 0x8c, 0x1f,
	0x31, 0xf1, 0x2e, 0xb4, 0x54, 0x6b, 0x3c, 0xc9, 0x1d, 0xbd, 0x87, 0xc6, 0x7a, 0xd2, 0x37, 0x80,
	0x78, 0xb3, 0xcd, 0x84, 0xc4, 0x19, 0x3e, 0x80, 0x75, 0x2b, 0x18, 0xef, 0x86, 0x5e, 0xf4, 0x20,
	0xe3, 0xdf, 0x4f, 0x46, 0x27, 0x0b, 0xb6, 0x12, 0x26, 0x23, 0x55, 0xd6, 0x12, 0xc4, 0x02, 0x14,
	0x7b, 0xb8, 0x3d, 0xdf, 0x28, 0x67, 0xf8, 0x0b, 0x30, 0xac, 0x60, 0xbc, 0xe3, 0xfb, 0x6f, 0xa1,
	0xfc, 0x54, 0x3a, 0xfa, 0x22, 0xe9, 0xec, 0x2b, 0xe9, 0xa0, 0xb2, 0x69, 0xce, 0xb6, 0xbf, 0x82,
	0xe6, 0x1e, 0x75, 0x0f, 0xd4, 0x4b, 0xa6, 0x05, 0x75, 0x35, 0x3d, 0x7c, 0xe3, 0x14, 0x5a, 0x01,
	0x78, 0xec, 0x04, 0xb1, 0x78, 0xb9, 0x26, 0xa1, 0xa1, 0x09, 0xd0, 0x4e, 0xc2, 0x30, 0x08, 0x07,
	0x86, 0x8e, 0x4e, 0x43, 0xe3, 0x93, 0x20, 0x0c, 0xf8, 0x53, 0xe2, 0x1b, 0x15, 0xb1, 0x12, 0xda,
	0x60, 0x02, 0x5b, 0x12, 0x44, 0xb9, 0x22, 0xbe, 0x51, 0xdd, 0xbe, 0x05, 0xad, 0x5c, 0xd9, 0xa0,
	0x26, 0x54, 0xef, 0x12, 0x37, 0x19, 0x18, 0xa7, 0x50, 0x03, 0x96, 0x44, 0xd1, 0x1b, 0x9a, 0xf8,
	0xf5, 0xd8, 0x89, 0x42, 0x43, 0x47, 0x75, 0xa8, 0x7c, 0x1c, 0x45, 0x46, 0xe5, 0xe6, 0xdf, 0x00,
	0x6b, 0x77, 0xe8, 0x68, 0x44, 0x43, 0x2b, 0x89, 0x63, 0x1a, 0x1e, 0x90, 0xe8, 0x45, 0xe0, 0x11,
	0x74, 0x98, 0x0e, 0x98, 0xdc, 0xbb, 0x1a, 0x5d, 0xcc, 0x05, 0x3c, 0xe7, 0xff, 0x25, 0xe6, 0xb1,
	0x38, 0x67, 0xf8, 0xea, 0x77, 0xbf, 0xff, 0xf9, 0x93, 0x7e, 0x09, 0x9b, 0x3d, 0x4b, 0xf0, 0xf6,
	0xa8, 0xdb, 0x2b, 0xd3, 0x6e, 0x6b, 0xdb, 0xe8, 0x39, 0xac, 0x14, 0xe7, 0x2b, 0xba, 0x50, 0x36,
	0x9c, 0x7f, 0x67, 0x98, 0xc7, 0xa0, 0x9c, 0xe1, 0xff, 0x49, 0xa7, 0x5b, 0xb8, 0x5d, 0x72, 0x3a,
	0x21, 0x09, 0x97, 0x23, 0x58, 0x2e, 0x8c, 0x53, 0xb4, 0x59, 0xb6, 0x99, 0xeb, 0x03, 0xe6, 0x62,
	0x90, 0x33, 0x8c, 0xa5, 0xbf, 0x0b, 0xf8, 0x7c, 0xc9, 0x5f, 0xc6, 0x11, 0xee, 0x02, 0x38, 0x9d,
	0x1f, 0xa9, 0xc8, 0x9c, 0x35, 0x98, 0x75, 0x0c, 0x73, 0x21, 0xc6, 0x19, 0xbe, 0x2c, 0x7d, 0x6d,
	0xe2, 0xf5, 0x19, 0x5f, 0x92, 0x22, 0x5c, 0x1d, 0x82, 0x51, 0x9e, 0xb9, 0x85, 0x7b, 0x9c, 0x33,
	0xc7, 0xcd, 0x63, 0xf1, 0xf9, 0xf7, 0x58, 0xa6, 0xa5, 0x51, 0xe6, 0xa7, 0x59, 0x21, 0xca, 0xd2,
	0xf0, 0x36, 0x17, 0x62, 0xf3, 0xa3, 0xcc, 0x53, 0x84, 0xab, 0x64, 0x3a, 0x38, 0xd3, 0x22, 0x40,
	0x5b, 0x73, 0x2c, 0x4e, 0x2b, 0xdd, 0x3c, 0x0e, 0xe6, 0x0c, 0x5f, 0x91, 0x3e, 0x2f, 0xe2, 0x8d,
	0x59, 0x9f, 0x29, 0x4b, 0xb8, 0x25, 0xd0, 0xca, 0x35, 0x7c, 0xb4, 0x91, 0x1f, 0xb5, 0x85, 0xd1,
	0x61, 0x2e, 0x82, 0x38, 0xc3, 0x1d, 0xe9, 0xca, 0xc4, 0xe7, 0xa6, 0xae, 0x72, 0x0c, 0xe1, 0xc6,
	0x01, 0x98, 0x0e, 0x05, 0xd4, 0x2e, 0x9b, 0x9a, 0x48, 0x65, 0x01, 0xc2, 0x19, 0xbe, 0x24, 0x7d,
	0x6c, 0xe0, 0xb3, 0x25, 0x1f, 0x79, 0x99, 0x94, 0x5b, 0x72, 0x41, 0x26, 0x73, 0x46, 0x90, 0x79,
	0x2c, 0x3e, 0x5f, 0x26, 0x65, 0x9a, 0x70, 0xfd, 0xbd, 0x9a, 0x70, 0xe5, 0x16, 0x8d, 0x2e, 0x17,
	0xcd, 0xcf, 0x99, 0x0b, 0xe6, 0x9b, 0x28, 0x9c, 0xe1, 0xae, 0x3c, 0x04, 0xc6, 0x5b, 0x85, 0x43,
	0x94, 0x99, 0x69, 0x0f, 0x28, 0x34, 0xed, 0x42, 0x0f, 0x28, 0x4f, 0x0a, 0x73, 0x31, 0x38, 0xbf,
	0x07, 0x14, 0x38, 0xb7, 0xb5, 0x6d, 0x0b, 0x7f, 0xd9, 0x19, 0x04, 0xf1, 0xd3, 0xc4, 0xbd, 0xee,
	0xd1, 0x51, 0x6f, 0x3c, 0x3c, 0x4c, 0x9c, 0xd0, 0x0b, 0x7b, 0x13, 0xab, 0x3d, 0xe6, 0xba, 0x35,
	0xf9, 0x77, 0xa0, 0x8f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x99, 0xc5, 0x51, 0xd0, 0x5c, 0x12,
	0x00, 0x00,
}
