// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.1
// source: hello.proto

package pb

import (
	context "context"
	pb "github.com/zlyuancn/batch_job/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HelloService_CreateCheck_FullMethodName = "/hello.HelloService/CreateCheck"
	HelloService_Start_FullMethodName       = "/hello.HelloService/Start"
	HelloService_Process_FullMethodName     = "/hello.HelloService/Process"
	HelloService_Stop_FullMethodName        = "/hello.HelloService/Stop"
)

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloServiceClient interface {
	// 创建检查
	CreateCheck(ctx context.Context, in *pb.JobBeforeCreateAndChangeReq, opts ...grpc.CallOption) (*pb.JobBeforeCreateAndChangeRsp, error)
	// 运行任务处理
	Start(ctx context.Context, in *pb.JobBeforeRunReq, opts ...grpc.CallOption) (*pb.JobBeforeRunRsp, error)
	// 处理数据
	Process(ctx context.Context, in *pb.JobProcessReq, opts ...grpc.CallOption) (*pb.JobProcessRsp, error)
	// 停止任务处理
	Stop(ctx context.Context, in *pb.JobProcessStopReq, opts ...grpc.CallOption) (*pb.JobProcessStopRsp, error)
}

type helloServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloServiceClient(cc grpc.ClientConnInterface) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) CreateCheck(ctx context.Context, in *pb.JobBeforeCreateAndChangeReq, opts ...grpc.CallOption) (*pb.JobBeforeCreateAndChangeRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.JobBeforeCreateAndChangeRsp)
	err := c.cc.Invoke(ctx, HelloService_CreateCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) Start(ctx context.Context, in *pb.JobBeforeRunReq, opts ...grpc.CallOption) (*pb.JobBeforeRunRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.JobBeforeRunRsp)
	err := c.cc.Invoke(ctx, HelloService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) Process(ctx context.Context, in *pb.JobProcessReq, opts ...grpc.CallOption) (*pb.JobProcessRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.JobProcessRsp)
	err := c.cc.Invoke(ctx, HelloService_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) Stop(ctx context.Context, in *pb.JobProcessStopReq, opts ...grpc.CallOption) (*pb.JobProcessStopRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.JobProcessStopRsp)
	err := c.cc.Invoke(ctx, HelloService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
// All implementations must embed UnimplementedHelloServiceServer
// for forward compatibility.
type HelloServiceServer interface {
	// 创建检查
	CreateCheck(context.Context, *pb.JobBeforeCreateAndChangeReq) (*pb.JobBeforeCreateAndChangeRsp, error)
	// 运行任务处理
	Start(context.Context, *pb.JobBeforeRunReq) (*pb.JobBeforeRunRsp, error)
	// 处理数据
	Process(context.Context, *pb.JobProcessReq) (*pb.JobProcessRsp, error)
	// 停止任务处理
	Stop(context.Context, *pb.JobProcessStopReq) (*pb.JobProcessStopRsp, error)
	mustEmbedUnimplementedHelloServiceServer()
}

// UnimplementedHelloServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHelloServiceServer struct{}

func (UnimplementedHelloServiceServer) CreateCheck(context.Context, *pb.JobBeforeCreateAndChangeReq) (*pb.JobBeforeCreateAndChangeRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCheck not implemented")
}
func (UnimplementedHelloServiceServer) Start(context.Context, *pb.JobBeforeRunReq) (*pb.JobBeforeRunRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedHelloServiceServer) Process(context.Context, *pb.JobProcessReq) (*pb.JobProcessRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedHelloServiceServer) Stop(context.Context, *pb.JobProcessStopReq) (*pb.JobProcessStopRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedHelloServiceServer) mustEmbedUnimplementedHelloServiceServer() {}
func (UnimplementedHelloServiceServer) testEmbeddedByValue()                      {}

// UnsafeHelloServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloServiceServer will
// result in compilation errors.
type UnsafeHelloServiceServer interface {
	mustEmbedUnimplementedHelloServiceServer()
}

func RegisterHelloServiceServer(s grpc.ServiceRegistrar, srv HelloServiceServer) {
	// If the following call pancis, it indicates UnimplementedHelloServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HelloService_ServiceDesc, srv)
}

func _HelloService_CreateCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.JobBeforeCreateAndChangeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).CreateCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelloService_CreateCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).CreateCheck(ctx, req.(*pb.JobBeforeCreateAndChangeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.JobBeforeRunReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelloService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Start(ctx, req.(*pb.JobBeforeRunReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.JobProcessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelloService_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Process(ctx, req.(*pb.JobProcessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.JobProcessStopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelloService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Stop(ctx, req.(*pb.JobProcessStopReq))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloService_ServiceDesc is the grpc.ServiceDesc for HelloService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCheck",
			Handler:    _HelloService_CreateCheck_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _HelloService_Start_Handler,
		},
		{
			MethodName: "Process",
			Handler:    _HelloService_Process_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _HelloService_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
