// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.1
// source: hello.proto

package pb

import (
	pb "github.com/zlyuancn/batch_job/pb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_hello_proto protoreflect.FileDescriptor

const file_hello_proto_rawDesc = "" +
	"\n" +
	"\vhello.proto\x12\x05hello\x1a\x1cgoogle/api/annotations.proto\x1a\x12pb/batch_job.proto2\x9c\x03\n" +
	"\fHelloService\x12|\n" +
	"\vCreateCheck\x12&.batch_job.JobBeforeCreateAndChangeReq\x1a&.batch_job.JobBeforeCreateAndChangeRsp\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/hello/CreateCheck\x12X\n" +
	"\x05Start\x12\x1a.batch_job.JobBeforeRunReq\x1a\x1a.batch_job.JobBeforeRunRsp\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/hello/Start\x12X\n" +
	"\aProcess\x12\x18.batch_job.JobProcessReq\x1a\x18.batch_job.JobProcessRsp\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/hello/Process\x12Z\n" +
	"\x04Stop\x12\x1c.batch_job.JobProcessStopReq\x1a\x1c.batch_job.JobProcessStopRsp\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/hello/StopB0Z.github.com/zlyuancn/batch_job/example/hello/pbb\x06proto3"

var file_hello_proto_goTypes = []any{
	(*pb.JobBeforeCreateAndChangeReq)(nil), // 0: batch_job.JobBeforeCreateAndChangeReq
	(*pb.JobBeforeRunReq)(nil),             // 1: batch_job.JobBeforeRunReq
	(*pb.JobProcessReq)(nil),               // 2: batch_job.JobProcessReq
	(*pb.JobProcessStopReq)(nil),           // 3: batch_job.JobProcessStopReq
	(*pb.JobBeforeCreateAndChangeRsp)(nil), // 4: batch_job.JobBeforeCreateAndChangeRsp
	(*pb.JobBeforeRunRsp)(nil),             // 5: batch_job.JobBeforeRunRsp
	(*pb.JobProcessRsp)(nil),               // 6: batch_job.JobProcessRsp
	(*pb.JobProcessStopRsp)(nil),           // 7: batch_job.JobProcessStopRsp
}
var file_hello_proto_depIdxs = []int32{
	0, // 0: hello.HelloService.CreateCheck:input_type -> batch_job.JobBeforeCreateAndChangeReq
	1, // 1: hello.HelloService.Start:input_type -> batch_job.JobBeforeRunReq
	2, // 2: hello.HelloService.Process:input_type -> batch_job.JobProcessReq
	3, // 3: hello.HelloService.Stop:input_type -> batch_job.JobProcessStopReq
	4, // 4: hello.HelloService.CreateCheck:output_type -> batch_job.JobBeforeCreateAndChangeRsp
	5, // 5: hello.HelloService.Start:output_type -> batch_job.JobBeforeRunRsp
	6, // 6: hello.HelloService.Process:output_type -> batch_job.JobProcessRsp
	7, // 7: hello.HelloService.Stop:output_type -> batch_job.JobProcessStopRsp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hello_proto_init() }
func file_hello_proto_init() {
	if File_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hello_proto_rawDesc), len(file_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hello_proto_goTypes,
		DependencyIndexes: file_hello_proto_depIdxs,
	}.Build()
	File_hello_proto = out.File
	file_hello_proto_goTypes = nil
	file_hello_proto_depIdxs = nil
}
